CREATE SCHEMA IF NOT EXISTS ordering;
CREATE TABLE IF NOT EXISTS ordering.addresses(id uuid PRIMARY KEY,customer_id uuid NOT NULL,recipient_name text NOT NULL,phone text NOT NULL,line1 text NOT NULL,line2 text NULL,city text NOT NULL,zone text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ordering.baskets(customer_id uuid PRIMARY KEY,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ordering.basket_items(customer_id uuid NOT NULL REFERENCES ordering.baskets(customer_id) ON DELETE CASCADE,product_id uuid NOT NULL,quantity integer NOT NULL CHECK(quantity>0),PRIMARY KEY(customer_id,product_id));
CREATE TABLE IF NOT EXISTS ordering.orders(id uuid PRIMARY KEY,customer_id uuid NOT NULL,address_snapshot jsonb NOT NULL,status text NOT NULL,subtotal numeric(12,2) NOT NULL,tax numeric(12,2) NOT NULL,delivery_fee numeric(12,2) NOT NULL,total numeric(12,2) NOT NULL,currency text NOT NULL DEFAULT 'USD',reservation_id uuid NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ordering.order_items(order_id uuid NOT NULL REFERENCES ordering.orders(id),product_id uuid NOT NULL,sku text NOT NULL,name text NOT NULL,unit_price numeric(12,2) NOT NULL,quantity integer NOT NULL CHECK(quantity>0),PRIMARY KEY(order_id,product_id));
CREATE TABLE IF NOT EXISTS ordering.order_status_history(id bigserial PRIMARY KEY,order_id uuid NOT NULL REFERENCES ordering.orders(id),status text NOT NULL,actor_id uuid NULL,reason text NULL,occurred_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ordering.checkout_keys(customer_id uuid NOT NULL,key text NOT NULL,request_hash text NOT NULL,order_id uuid NOT NULL UNIQUE REFERENCES ordering.orders(id),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(customer_id,key));
CREATE TABLE IF NOT EXISTS ordering.outbox(event_id uuid PRIMARY KEY,event_type text NOT NULL,payload jsonb NOT NULL,occurred_at timestamptz NOT NULL DEFAULT now(),published_at timestamptz NULL);
