using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Net.Http.Json;
using Confluent.Kafka;
using Npgsql;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddSingleton(_ => NpgsqlDataSource.Create(builder.Configuration.GetConnectionString("Order") ?? "Host=localhost;Port=5432;Database=marketflow;Username=marketflow;Password=marketflow;Search Path=ordering"));
builder.Services.AddHttpClient<IdentityClient>(c => c.BaseAddress = new Uri(builder.Configuration["Services:IdentityUrl"] ?? "http://localhost:8081"));
builder.Services.AddHttpClient<CatalogClient>(c => c.BaseAddress = new Uri(builder.Configuration["Services:CatalogUrl"] ?? "http://localhost:8082"));
builder.Services.AddSingleton<RequestMetrics>();
builder.Services.AddHostedService<OutboxPublisher>();
builder.Services.AddHostedService<PendingOrderReconciler>();
var app = builder.Build();
app.Use(async (context, next) => { var correlation = context.Request.Headers["X-Correlation-Id"].FirstOrDefault() ?? Guid.NewGuid().ToString(); context.Response.Headers["X-Correlation-Id"] = correlation; var stopwatch = System.Diagnostics.Stopwatch.StartNew(); using (app.Logger.BeginScope(new Dictionary<string, object?> { ["CorrelationId"] = correlation })) { try { await next(); } finally { context.RequestServices.GetRequiredService<RequestMetrics>().Record(context.Response.StatusCode, stopwatch.Elapsed); } } });
if (app.Environment.IsDevelopment() || builder.Configuration.GetValue<bool>("Migrations:ApplyOnStartup"))
    await OrderDb.InitializeAsync(app.Services.GetRequiredService<NpgsqlDataSource>());
if (builder.Configuration.GetValue<bool>("Migrations:ExitAfterApply")) return;

app.MapGet("/health", () => Results.Ok(new { status = "healthy", service = "order" }));
app.MapGet("/health/ready", async (NpgsqlDataSource db, IConfiguration cfg) => await DependencyHealth.Ready(db, cfg, "order"));
app.MapGet("/metrics", async (RequestMetrics m, NpgsqlDataSource db) => Results.Text(m.AsPrometheus("order", await OrderDb.OperationalMetrics(db)), "text/plain"));
app.MapGet("/openapi/v1.json", () => Results.Text(OpenApi.Document("MarketFlow Order API", new("get", "/health", "Liveness check"), new("get", "/health/ready", "Dependency readiness check"), new("get", "/addresses", "List customer addresses"), new("post", "/addresses", "Create an address"), new("put", "/addresses/{id}", "Update an address"), new("delete", "/addresses/{id}", "Delete an address"), new("get", "/basket", "Read the basket"), new("put", "/basket/items/{productId}", "Set basket item quantity"), new("post", "/orders", "Submit checkout"), new("get", "/orders", "List orders"), new("get", "/reports/sales", "Run the sales report"), new("get", "/reports/sales/export", "Export the sales report")), "application/json"));
app.MapGet("/swagger", () => Results.Content(OpenApi.Ui, "text/html"));
app.MapGet("/addresses", async (HttpRequest req, IdentityClient auth, NpgsqlDataSource db) => { var user = await auth.Customer(req); return user is null ? Results.Unauthorized() : Results.Ok(await OrderDb.Addresses(db, user.Subject)); });
app.MapGet("/addresses/{id:guid}", async (Guid id, HttpRequest req, IdentityClient auth, NpgsqlDataSource db) => { var user = await auth.Customer(req); if (user is null) return Results.Unauthorized(); var address = await OrderDb.Address(db, user.Subject, id); return address is null ? Results.NotFound() : Results.Ok(address); });
app.MapPost("/addresses", async (AddressInput input, HttpRequest req, IdentityClient auth, NpgsqlDataSource db) => { var user = await auth.Customer(req); if (user is null) return Results.Unauthorized(); var errors = AddressInput.Validate(input); if (errors.Count > 0) return Results.ValidationProblem(errors); var id = await OrderDb.SaveAddress(db, user.Subject, null, input); return Results.Created($"/addresses/{id}", new { id }); });
app.MapPut("/addresses/{id:guid}", async (Guid id, AddressInput input, HttpRequest req, IdentityClient auth, NpgsqlDataSource db) => { var user = await auth.Customer(req); if (user is null) return Results.Unauthorized(); var errors = AddressInput.Validate(input); if (errors.Count > 0) return Results.ValidationProblem(errors); return await OrderDb.SaveAddress(db, user.Subject, id, input) == Guid.Empty ? Results.NotFound() : Results.NoContent(); });
app.MapDelete("/addresses/{id:guid}", async (Guid id, HttpRequest req, IdentityClient auth, NpgsqlDataSource db) => { var user = await auth.Customer(req); if (user is null) return Results.Unauthorized(); return await OrderDb.DeleteAddress(db, user.Subject, id) ? Results.NoContent() : Results.NotFound(); });
app.MapGet("/basket", async (HttpRequest req, IdentityClient auth, NpgsqlDataSource db, CatalogClient catalog) => { var user = await auth.Customer(req); return user is null ? Results.Unauthorized() : Results.Ok(await OrderDb.Basket(db, user.Subject, catalog)); });
app.MapPut("/basket/items/{productId:guid}", async (Guid productId, BasketLineInput input, HttpRequest req, IdentityClient auth, NpgsqlDataSource db, CatalogClient catalog) => { var user = await auth.Customer(req); if (user is null) return Results.Unauthorized(); if (input.Quantity <= 0) return Results.ValidationProblem(new Dictionary<string, string[]> { ["quantity"] = ["Quantity must be positive."] }); if (await catalog.Product(productId) is null) return Results.BadRequest(new { message = "Product is not available." }); await OrderDb.SetBasketLine(db, user.Subject, productId, input.Quantity); return Results.Ok(await OrderDb.Basket(db, user.Subject, catalog)); });
app.MapDelete("/basket/items/{productId:guid}", async (Guid productId, HttpRequest req, IdentityClient auth, NpgsqlDataSource db, CatalogClient catalog) => { var user = await auth.Customer(req); if (user is null) return Results.Unauthorized(); await OrderDb.RemoveBasketLine(db, user.Subject, productId); return Results.Ok(await OrderDb.Basket(db, user.Subject, catalog)); });
app.MapPost("/orders", async (CheckoutInput input, HttpRequest req, IdentityClient auth, NpgsqlDataSource db, CatalogClient catalog) =>
{
    var user = await auth.Customer(req); if (user is null) return Results.Unauthorized(); var key = req.Headers["Idempotency-Key"].FirstOrDefault(); if (string.IsNullOrWhiteSpace(key) || key.Length > 160) return Results.ValidationProblem(new Dictionary<string, string[]> { ["Idempotency-Key"] = ["A non-empty idempotency key of at most 160 characters is required."] });
    var result = await OrderDb.Checkout(db, user.Subject, key, input, catalog, CorrelationId.From(req));
    return result.Error is "Conflict" ? Results.Conflict(result) : result.Status == "Rejected" ? Results.UnprocessableEntity(result) : Results.Ok(result);
});
app.MapGet("/orders", async (HttpRequest req, IdentityClient auth, NpgsqlDataSource db) => { var user = await auth.Customer(req); return user is null ? Results.Unauthorized() : Results.Ok(await OrderDb.Orders(db, user.Subject)); });
app.MapGet("/orders/{id:guid}", async (Guid id, HttpRequest req, IdentityClient auth, NpgsqlDataSource db) => { var user = await auth.Customer(req); if (user is null) return Results.Unauthorized(); var order = await OrderDb.Order(db, id, user.Subject, false); return order is null ? Results.NotFound() : Results.Ok(order); });
app.MapPost("/orders/{id:guid}/cancel", async (Guid id, CancelInput input, HttpRequest req, IdentityClient auth, NpgsqlDataSource db, CatalogClient catalog) => { var user = await auth.Customer(req); if (user is null) return Results.Unauthorized(); return await CancelOrder(db, catalog, id, user.Subject, input.Reason, false, CorrelationId.From(req)); });
app.MapGet("/staff/orders", async (HttpRequest req, IdentityClient auth, NpgsqlDataSource db) => !await auth.Allowed(req, "OperationsAdmin") ? Results.Forbid() : Results.Ok(await OrderDb.StaffOrders(db)));
app.MapPost("/staff/orders/{id:guid}/cancel", async (Guid id, CancelInput input, HttpRequest req, IdentityClient auth, NpgsqlDataSource db, CatalogClient catalog) => { var admin = await auth.Principal(req, "OperationsAdmin"); if (admin is null) return Results.Forbid(); return await CancelOrder(db, catalog, id, admin.Subject, input.Reason, true, CorrelationId.From(req)); });
app.MapGet("/reports/sales", async (DateTimeOffset? from, DateTimeOffset? to, string? status, HttpRequest req, IdentityClient auth, NpgsqlDataSource db) => { if (!await auth.Allowed(req, "OperationsAdmin")) return Results.Forbid(); if (from is not null && to is not null && from >= to) return Results.BadRequest(new { message = "from must precede to." }); return Results.Ok(await OrderDb.Sales(db, from, to, status)); });
app.MapGet("/reports/sales/export", async (DateTimeOffset? from, DateTimeOffset? to, string? status, HttpRequest req, IdentityClient auth, NpgsqlDataSource db) => { if (!await auth.Allowed(req, "OperationsAdmin")) return Results.Forbid(); if (from is not null && to is not null && from >= to) return Results.BadRequest(new { message = "from must precede to." }); var report = await OrderDb.Sales(db, from, to, status); var csv = new StringBuilder("Order ID,Created At,Status,Subtotal,Tax,Delivery Fee,Total,Currency\n"); foreach (var row in report.Orders) csv.Append(row.Id).Append(',').Append(row.CreatedAt.ToString("O")).Append(',').Append(row.Status).Append(',').Append(row.Subtotal.ToString("0.00", CultureInfo.InvariantCulture)).Append(',').Append(row.Tax.ToString("0.00", CultureInfo.InvariantCulture)).Append(',').Append(row.DeliveryFee.ToString("0.00", CultureInfo.InvariantCulture)).Append(',').Append(row.Total.ToString("0.00", CultureInfo.InvariantCulture)).Append(',').Append(row.Currency).Append('\n'); return Results.File(Encoding.UTF8.GetBytes(csv.ToString()), "text/csv", "sales-report.csv"); });
app.Run();

static async Task<IResult> CancelOrder(NpgsqlDataSource db, CatalogClient catalog, Guid id, Guid actor, string reason, bool staff, Guid correlation)
{
    if (string.IsNullOrWhiteSpace(reason)) return Results.ValidationProblem(new Dictionary<string, string[]> { ["reason"] = ["Cancellation reason is required."] });
    var order = await OrderDb.Order(db, id, actor, staff); if (order is null) return Results.NotFound();
    if (order.Status != "Confirmed") return Results.Conflict(new { message = "Only confirmed orders can be cancelled." });
    if (!await OrderDb.BeginCancellation(db, id, actor, reason)) return Results.Conflict(new { message = "Order state changed; refresh and try again." });
    var release = await catalog.Release(id, correlation);
    if (release?.State != "Released") { await OrderDb.RestoreConfirmed(db, id, actor, "Stock release was not confirmed."); return Results.Conflict(new { message = "Stock release did not complete; order remains confirmed." }); }
    await OrderDb.Finish(db, id, "Cancelled", actor, reason, correlation, false); return Results.NoContent();
}

record Principal(Guid Subject, string[] Roles);
record AddressInput(string RecipientName, string Phone, string Line1, string? Line2, string City, string Zone)
{
    public static Dictionary<string, string[]> Validate(AddressInput x) { var errors = new Dictionary<string, string[]>(); if (string.IsNullOrWhiteSpace(x.RecipientName) || string.IsNullOrWhiteSpace(x.Phone) || string.IsNullOrWhiteSpace(x.Line1) || string.IsNullOrWhiteSpace(x.City) || string.IsNullOrWhiteSpace(x.Zone)) errors["address"] = ["Recipient, phone, line 1, city and zone are required."]; return errors; }
}
record BasketLineInput(int Quantity); record CheckoutInput(Guid AddressId); record CancelInput(string Reason); record ReservationLine(Guid ProductId, int Quantity);
record ProductDto(Guid Id, string Sku, string Name, decimal Price, int StockQuantity, bool Active);
record BasketLineView(Guid ProductId, string Sku, string Name, decimal UnitPrice, int Quantity, decimal LineTotal, bool Available);
record BasketView(List<BasketLineView> Lines, decimal Subtotal, decimal Tax, decimal DeliveryFee, decimal Total, string Currency);
record CheckoutResult(Guid OrderId, string Status, decimal Subtotal, decimal Tax, decimal DeliveryFee, decimal Total, string? Error = null);
record ReservationResponse(Guid OrderId, Guid? ReservationId, string State);
record SalesRow(Guid Id, DateTimeOffset CreatedAt, string Status, decimal Subtotal, decimal Tax, decimal DeliveryFee, decimal Total, string Currency);
record SalesReport(int OrderCount, decimal RecognizedSales, decimal Tax, decimal DeliveryFee, DateTimeOffset GeneratedAt, List<SalesRow> Orders);
static class CorrelationId { public static Guid From(HttpRequest request) => Guid.TryParse(request.Headers["X-Correlation-Id"].FirstOrDefault(), out var id) ? id : Guid.NewGuid(); }

sealed class IdentityClient(HttpClient http)
{
    public async Task<Principal?> Customer(HttpRequest request) => await Principal(request, "Customer");
    public async Task<bool> Allowed(HttpRequest request, params string[] roles) => await Principal(request, roles) is not null;
    public async Task<Principal?> Principal(HttpRequest request, params string[] roles) { var token = request.Headers.Authorization.FirstOrDefault(); if (string.IsNullOrWhiteSpace(token)) return null; using var message = new HttpRequestMessage(HttpMethod.Get, "/auth/introspect"); message.Headers.TryAddWithoutValidation("Authorization", token); try { var result = await http.SendAsync(message); if (!result.IsSuccessStatusCode) return null; var root = JsonDocument.Parse(await result.Content.ReadAsStringAsync()).RootElement; if (!root.GetProperty("active").GetBoolean()) return null; var found = root.GetProperty("roles").EnumerateArray().Select(x => x.GetString()!).ToArray(); return roles.Any(found.Contains) ? new Principal(root.GetProperty("subject").GetGuid(), found) : null; } catch { return null; } }
}
sealed class CatalogClient(HttpClient http, IConfiguration config)
{
    string Key => config["Internal:CatalogKey"] ?? string.Empty;
    public async Task<ProductDto?> Product(Guid id) { try { var p = await http.GetFromJsonAsync<JsonElement>($"/products/{id}"); return p.ValueKind == JsonValueKind.Undefined ? null : new ProductDto(p.GetProperty("id").GetGuid(), p.GetProperty("sku").GetString()!, p.GetProperty("name").GetString()!, p.GetProperty("price").GetDecimal(), p.GetProperty("stockQuantity").GetInt32(), p.GetProperty("active").GetBoolean()); } catch { return null; } }
    public async Task<ReservationResponse?> Reserve(Guid orderId, List<ReservationLine> lines, Guid correlation) { if (string.IsNullOrWhiteSpace(Key)) return null; using var msg = new HttpRequestMessage(HttpMethod.Post, "/internal/stock-reservations") { Content = JsonContent.Create(new { orderId, lines, correlationId = correlation }) }; msg.Headers.Add("X-Internal-Key", Key); var result = await http.SendAsync(msg); return result.IsSuccessStatusCode ? await result.Content.ReadFromJsonAsync<ReservationResponse>() : null; }
    public async Task<ReservationResponse?> Release(Guid orderId, Guid correlation) { if (string.IsNullOrWhiteSpace(Key)) return null; using var msg = new HttpRequestMessage(HttpMethod.Post, $"/internal/stock-reservations/{orderId}/release") { Content = JsonContent.Create(new { correlationId = correlation }) }; msg.Headers.Add("X-Internal-Key", Key); var result = await http.SendAsync(msg); return result.IsSuccessStatusCode ? await result.Content.ReadFromJsonAsync<ReservationResponse>() : null; }
    public async Task<ReservationResponse?> Reservation(Guid orderId) { if (string.IsNullOrWhiteSpace(Key)) return null; using var msg = new HttpRequestMessage(HttpMethod.Get, $"/internal/stock-reservations/by-order/{orderId}"); msg.Headers.Add("X-Internal-Key", Key); var result = await http.SendAsync(msg); return result.IsSuccessStatusCode ? await result.Content.ReadFromJsonAsync<ReservationResponse>() : null; }
}

static class OrderDb
{
    public static async Task InitializeAsync(NpgsqlDataSource db)
    {
        await using (var history = db.CreateCommand("CREATE SCHEMA IF NOT EXISTS ordering; CREATE TABLE IF NOT EXISTS ordering.schema_migrations(version text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());")) await history.ExecuteNonQueryAsync();
        await using var conn = await db.OpenConnectionAsync();
        await using var tx = await conn.BeginTransactionAsync();
        await using var claim = new NpgsqlCommand("INSERT INTO ordering.schema_migrations(version) VALUES('001_baseline') ON CONFLICT DO NOTHING RETURNING version", conn, tx);
        if (await claim.ExecuteScalarAsync() is not null)
        {
            var sql = await MigrationSql.BaselineAsync();
            await using var cmd = new NpgsqlCommand(sql, conn, tx); await cmd.ExecuteNonQueryAsync();
        }
        await tx.CommitAsync();
        await ApplyMigration(db, "002_checkout_key_address", MigrationSql.CheckoutKeyAddressAsync);
    }
    static async Task ApplyMigration(NpgsqlDataSource db, string version, Func<Task<string>> readSql)
    {
        await using var conn = await db.OpenConnectionAsync(); await using var tx = await conn.BeginTransactionAsync();
        await using var claim = new NpgsqlCommand("INSERT INTO ordering.schema_migrations(version) VALUES($1) ON CONFLICT DO NOTHING RETURNING version", conn, tx); claim.Parameters.AddWithValue(version);
        if (await claim.ExecuteScalarAsync() is not null) { await using var command = new NpgsqlCommand(await readSql(), conn, tx); await command.ExecuteNonQueryAsync(); }
        await tx.CommitAsync();
    }
    public static async Task<OperationalMetrics> OperationalMetrics(NpgsqlDataSource db) { await using var cmd = db.CreateCommand("SELECT (SELECT count(*) FROM ordering.outbox WHERE published_at IS NULL), (SELECT count(*) FROM ordering.orders WHERE status='PendingReservation')"); await using var reader = await cmd.ExecuteReaderAsync(); await reader.ReadAsync(); return new OperationalMetrics(reader.GetInt64(0), reader.GetInt64(1)); }
    public static async Task<List<object>> Addresses(NpgsqlDataSource db, Guid owner) { await using var cmd = db.CreateCommand("SELECT id,recipient_name,phone,line1,line2,city,zone FROM addresses WHERE customer_id=$1 ORDER BY updated_at DESC"); cmd.Parameters.AddWithValue(owner); await using var reader = await cmd.ExecuteReaderAsync(); var rows = new List<object>(); while (await reader.ReadAsync()) rows.Add(AddressRow(reader)); return rows; }
    public static async Task<object?> Address(NpgsqlDataSource db, Guid owner, Guid id) { await using var cmd = db.CreateCommand("SELECT id,recipient_name,phone,line1,line2,city,zone FROM addresses WHERE id=$1 AND customer_id=$2"); cmd.Parameters.AddWithValue(id); cmd.Parameters.AddWithValue(owner); await using var reader = await cmd.ExecuteReaderAsync(); return await reader.ReadAsync() ? AddressRow(reader) : null; }
    static object AddressRow(NpgsqlDataReader reader) => new { id = reader.GetGuid(0), recipientName = reader.GetString(1), phone = reader.GetString(2), line1 = reader.GetString(3), line2 = reader.IsDBNull(4) ? null : reader.GetString(4), city = reader.GetString(5), zone = reader.GetString(6) };
    public static async Task<Guid> SaveAddress(NpgsqlDataSource db, Guid owner, Guid? id, AddressInput input) { var value = id ?? Guid.NewGuid(); await using var cmd = db.CreateCommand(id is null ? "INSERT INTO addresses(id,customer_id,recipient_name,phone,line1,line2,city,zone) VALUES($1,$2,$3,$4,$5,$6,$7,$8)" : "UPDATE addresses SET recipient_name=$3,phone=$4,line1=$5,line2=$6,city=$7,zone=$8,updated_at=now() WHERE id=$1 AND customer_id=$2"); cmd.Parameters.AddWithValue(value); cmd.Parameters.AddWithValue(owner); cmd.Parameters.AddWithValue(input.RecipientName.Trim()); cmd.Parameters.AddWithValue(input.Phone.Trim()); cmd.Parameters.AddWithValue(input.Line1.Trim()); cmd.Parameters.AddWithValue((object?)input.Line2?.Trim() ?? DBNull.Value); cmd.Parameters.AddWithValue(input.City.Trim()); cmd.Parameters.AddWithValue(input.Zone.Trim()); return await cmd.ExecuteNonQueryAsync() == 0 ? Guid.Empty : value; }
    public static async Task<bool> DeleteAddress(NpgsqlDataSource db, Guid owner, Guid id) { await using var cmd = db.CreateCommand("DELETE FROM addresses WHERE id=$1 AND customer_id=$2"); cmd.Parameters.AddWithValue(id); cmd.Parameters.AddWithValue(owner); return await cmd.ExecuteNonQueryAsync() == 1; }
    public static async Task SetBasketLine(NpgsqlDataSource db, Guid owner, Guid product, int quantity) { await using var conn = await db.OpenConnectionAsync(); await using var tx = await conn.BeginTransactionAsync(); await using (var basket = new NpgsqlCommand("INSERT INTO baskets(customer_id) VALUES($1) ON CONFLICT(customer_id) DO UPDATE SET updated_at=now()", conn, tx)) { basket.Parameters.AddWithValue(owner); await basket.ExecuteNonQueryAsync(); } await using (var item = new NpgsqlCommand("INSERT INTO basket_items(customer_id,product_id,quantity) VALUES($1,$2,$3) ON CONFLICT(customer_id,product_id) DO UPDATE SET quantity=excluded.quantity", conn, tx)) { item.Parameters.AddWithValue(owner); item.Parameters.AddWithValue(product); item.Parameters.AddWithValue(quantity); await item.ExecuteNonQueryAsync(); } await tx.CommitAsync(); }
    public static async Task RemoveBasketLine(NpgsqlDataSource db, Guid owner, Guid product) { await using var cmd = db.CreateCommand("DELETE FROM basket_items WHERE customer_id=$1 AND product_id=$2"); cmd.Parameters.AddWithValue(owner); cmd.Parameters.AddWithValue(product); await cmd.ExecuteNonQueryAsync(); }
    public static async Task<BasketView> Basket(NpgsqlDataSource db, Guid owner, CatalogClient catalog) { await using var cmd = db.CreateCommand("SELECT product_id,quantity FROM basket_items WHERE customer_id=$1 ORDER BY product_id"); cmd.Parameters.AddWithValue(owner); await using var reader = await cmd.ExecuteReaderAsync(); var raw = new List<(Guid ProductId, int Quantity)>(); while (await reader.ReadAsync()) raw.Add((reader.GetGuid(0), reader.GetInt32(1))); var lines = new List<BasketLineView>(); decimal subtotal = 0; foreach (var item in raw) { var product = await catalog.Product(item.ProductId); if (product is null) { lines.Add(new BasketLineView(item.ProductId, "", "Unavailable product", 0, item.Quantity, 0, false)); continue; } var total = product.Price * item.Quantity; subtotal += total; lines.Add(new BasketLineView(product.Id, product.Sku, product.Name, product.Price, item.Quantity, total, product.Active && product.StockQuantity >= item.Quantity)); } var totals = CheckoutRules.Calculate(subtotal); return new BasketView(lines, totals.Subtotal, totals.Tax, totals.DeliveryFee, totals.Total, "USD"); }
    public static async Task<CheckoutResult> Checkout(NpgsqlDataSource db, Guid owner, string key, CheckoutInput input, CatalogClient catalog, Guid correlation)
    {
        var address = await Address(db, owner, input.AddressId); if (address is null) return new CheckoutResult(Guid.Empty, "Rejected", 0, 0, 0, 0, "Choose one of your saved addresses.");
        var existing = await ExistingKey(db, owner, key); if (existing is not null) { if (existing.Value.AddressId != input.AddressId) return new CheckoutResult(existing.Value.OrderId, "Conflict", 0, 0, 0, 0, "Idempotency key was used with a different request."); return await ResultForOrder(db, existing.Value.OrderId); }
        var basket = await Basket(db, owner, catalog); if (basket.Lines.Count == 0 || basket.Lines.Any(x => !x.Available)) return new CheckoutResult(Guid.Empty, "Rejected", 0, 0, 0, 0, "Basket has unavailable items.");
        var hash = RequestHash(input.AddressId, basket);
        var orderId = Guid.NewGuid();
        try { await WritePending(db, orderId, owner, key, hash, new { Id = input.AddressId, Snapshot = address }, basket); }
        catch (PostgresException e) when (e.SqlState == "23505") { var duplicate = await ExistingKey(db, owner, key); if (duplicate is null) throw; return duplicate.Value.AddressId == input.AddressId ? await ResultForOrder(db, duplicate.Value.OrderId) : new CheckoutResult(duplicate.Value.OrderId, "Conflict", 0, 0, 0, 0, "Idempotency key was used with a different request."); }
        var reservation = await catalog.Reserve(orderId, basket.Lines.Select(x => new ReservationLine(x.ProductId, x.Quantity)).ToList(), correlation);
        if (reservation is null) return await ResultForOrder(db, orderId, "Reservation is pending reconciliation.");
        if (reservation.State == "Reserved") { await Finish(db, orderId, "Confirmed", owner, "Stock reserved", correlation, true); return await ResultForOrder(db, orderId); }
        await Finish(db, orderId, "Rejected", owner, "Stock unavailable", correlation, false); return await ResultForOrder(db, orderId, "Stock is no longer available.");
    }
    static string RequestHash(Guid addressId, BasketView basket) => CheckoutRules.IntentHash(addressId, basket.Lines.Select(x => new CheckoutLine(x.ProductId, x.Quantity, x.UnitPrice)), basket.Currency, basket.Tax, basket.DeliveryFee);
    static async Task<(string Hash, Guid OrderId, Guid AddressId)?> ExistingKey(NpgsqlDataSource db, Guid owner, string key) { await using var cmd = db.CreateCommand("SELECT request_hash,order_id,address_id FROM checkout_keys WHERE customer_id=$1 AND key=$2"); cmd.Parameters.AddWithValue(owner); cmd.Parameters.AddWithValue(key); await using var reader = await cmd.ExecuteReaderAsync(); return await reader.ReadAsync() ? (reader.GetString(0), reader.GetGuid(1), reader.GetGuid(2)) : null; }
    static async Task WritePending(NpgsqlDataSource db, Guid orderId, Guid owner, string key, string hash, object address, BasketView basket)
    {
        await using var conn = await db.OpenConnectionAsync(); await using var tx = await conn.BeginTransactionAsync();
        await using (var order = new NpgsqlCommand("INSERT INTO ordering.orders(id,customer_id,address_snapshot,status,subtotal,tax,delivery_fee,total,currency) VALUES($1,$2,CAST($3 AS jsonb),'PendingReservation',$4,$5,$6,$7,$8)", conn, tx))
        { order.Parameters.AddWithValue(orderId); order.Parameters.AddWithValue(owner); order.Parameters.AddWithValue(JsonSerializer.Serialize(((dynamic)address).Snapshot)); order.Parameters.AddWithValue(basket.Subtotal); order.Parameters.AddWithValue(basket.Tax); order.Parameters.AddWithValue(basket.DeliveryFee); order.Parameters.AddWithValue(basket.Total); order.Parameters.AddWithValue(basket.Currency); await order.ExecuteNonQueryAsync(); }
        await using (var checkoutKey = new NpgsqlCommand("INSERT INTO ordering.checkout_keys(customer_id,key,request_hash,order_id,address_id) VALUES($1,$2,$3,$4,$5)", conn, tx))
        { checkoutKey.Parameters.AddWithValue(owner); checkoutKey.Parameters.AddWithValue(key); checkoutKey.Parameters.AddWithValue(hash); checkoutKey.Parameters.AddWithValue(orderId); checkoutKey.Parameters.AddWithValue(((dynamic)address).Id); await checkoutKey.ExecuteNonQueryAsync(); }
        await using (var history = new NpgsqlCommand("INSERT INTO ordering.order_status_history(order_id,status,actor_id,reason) VALUES($1,'PendingReservation',$2,'Checkout received')", conn, tx))
        { history.Parameters.AddWithValue(orderId); history.Parameters.AddWithValue(owner); await history.ExecuteNonQueryAsync(); }
        foreach (var line in basket.Lines) { await using var item = new NpgsqlCommand("INSERT INTO ordering.order_items(order_id,product_id,sku,name,unit_price,quantity) VALUES($1,$2,$3,$4,$5,$6)", conn, tx); item.Parameters.AddWithValue(orderId); item.Parameters.AddWithValue(line.ProductId); item.Parameters.AddWithValue(line.Sku); item.Parameters.AddWithValue(line.Name); item.Parameters.AddWithValue(line.UnitPrice); item.Parameters.AddWithValue(line.Quantity); await item.ExecuteNonQueryAsync(); }
        await tx.CommitAsync();
    }
    public static async Task Finish(NpgsqlDataSource db, Guid orderId, string state, Guid actor, string reason, Guid correlation, bool clearBasket) { await using var conn = await db.OpenConnectionAsync(); await using var tx = await conn.BeginTransactionAsync(); var eventType = state == "Confirmed" ? "OrderPlaced" : state == "Cancelled" ? "OrderCancelled" : "OrderRejected"; await using var read = new NpgsqlCommand("UPDATE ordering.orders SET status=$2,updated_at=now() WHERE id=$1 RETURNING customer_id,subtotal,tax,delivery_fee,total,currency", conn, tx); read.Parameters.AddWithValue(orderId); read.Parameters.AddWithValue(state); await using var reader = await read.ExecuteReaderAsync(); if (!await reader.ReadAsync()) return; var customer = reader.GetGuid(0); var subtotal = reader.GetDecimal(1); var tax = reader.GetDecimal(2); var fee = reader.GetDecimal(3); var total = reader.GetDecimal(4); var currency = reader.GetString(5); await reader.CloseAsync(); await using (var history = new NpgsqlCommand("INSERT INTO ordering.order_status_history(order_id,status,actor_id,reason) VALUES($1,$2,$3,$4)", conn, tx)) { history.Parameters.AddWithValue(orderId); history.Parameters.AddWithValue(state); history.Parameters.AddWithValue(actor); history.Parameters.AddWithValue(reason); await history.ExecuteNonQueryAsync(); } var eventId = Guid.NewGuid(); var payload = JsonSerializer.Serialize(new { eventId, schemaVersion = 1, eventType, occurredAt = DateTimeOffset.UtcNow, correlationId = correlation, orderId, customerId = customer, status = state, subtotal, tax, deliveryFee = fee, total, currency }); await using (var outbox = new NpgsqlCommand("INSERT INTO ordering.outbox(event_id,event_type,payload) VALUES($1,$2,CAST($3 AS jsonb))", conn, tx)) { outbox.Parameters.AddWithValue(eventId); outbox.Parameters.AddWithValue(eventType); outbox.Parameters.AddWithValue(payload); await outbox.ExecuteNonQueryAsync(); } if (clearBasket) { await using var clear = new NpgsqlCommand("DELETE FROM ordering.basket_items WHERE customer_id=$1", conn, tx); clear.Parameters.AddWithValue(customer); await clear.ExecuteNonQueryAsync(); } await tx.CommitAsync(); }
    public static async Task<bool> BeginCancellation(NpgsqlDataSource db, Guid id, Guid actor, string reason) { await using var conn = await db.OpenConnectionAsync(); await using var tx = await conn.BeginTransactionAsync(); await using var update = new NpgsqlCommand("UPDATE ordering.orders SET status='CancellationPending',updated_at=now() WHERE id=$1 AND status='Confirmed'", conn, tx); update.Parameters.AddWithValue(id); if (await update.ExecuteNonQueryAsync() == 0) return false; await using var history = new NpgsqlCommand("INSERT INTO ordering.order_status_history(order_id,status,actor_id,reason) VALUES($1,'CancellationPending',$2,$3)", conn, tx); history.Parameters.AddWithValue(id); history.Parameters.AddWithValue(actor); history.Parameters.AddWithValue(reason); await history.ExecuteNonQueryAsync(); await tx.CommitAsync(); return true; }
    public static async Task RestoreConfirmed(NpgsqlDataSource db, Guid id, Guid actor, string reason) { await using var conn = await db.OpenConnectionAsync(); await using var tx = await conn.BeginTransactionAsync(); await using (var update = new NpgsqlCommand("UPDATE ordering.orders SET status='Confirmed',updated_at=now() WHERE id=$1 AND status='CancellationPending'", conn, tx)) { update.Parameters.AddWithValue(id); if (await update.ExecuteNonQueryAsync() == 0) return; } await using (var history = new NpgsqlCommand("INSERT INTO ordering.order_status_history(order_id,status,actor_id,reason) VALUES($1,'Confirmed',$2,$3)", conn, tx)) { history.Parameters.AddWithValue(id); history.Parameters.AddWithValue(actor); history.Parameters.AddWithValue(reason); await history.ExecuteNonQueryAsync(); } await tx.CommitAsync(); }
    public static async Task<List<object>> Orders(NpgsqlDataSource db, Guid owner) { await using var cmd = db.CreateCommand("SELECT id,status,total,created_at FROM ordering.orders WHERE customer_id=$1 ORDER BY created_at DESC"); cmd.Parameters.AddWithValue(owner); await using var reader = await cmd.ExecuteReaderAsync(); var rows = new List<object>(); while (await reader.ReadAsync()) rows.Add(new { id = reader.GetGuid(0), status = reader.GetString(1), total = reader.GetDecimal(2), createdAt = reader.GetFieldValue<DateTimeOffset>(3) }); return rows; }
    public static async Task<dynamic?> Order(NpgsqlDataSource db, Guid id, Guid owner, bool staff) { await using var cmd = db.CreateCommand(staff ? "SELECT id,status,subtotal,tax,delivery_fee,total,created_at FROM ordering.orders WHERE id=$1" : "SELECT id,status,subtotal,tax,delivery_fee,total,created_at FROM ordering.orders WHERE id=$1 AND customer_id=$2"); cmd.Parameters.AddWithValue(id); if (!staff) cmd.Parameters.AddWithValue(owner); await using var reader = await cmd.ExecuteReaderAsync(); return await reader.ReadAsync() ? new { Id = reader.GetGuid(0), Status = reader.GetString(1), Subtotal = reader.GetDecimal(2), Tax = reader.GetDecimal(3), DeliveryFee = reader.GetDecimal(4), Total = reader.GetDecimal(5), CreatedAt = reader.GetFieldValue<DateTimeOffset>(6) } : null; }
    public static async Task<List<object>> StaffOrders(NpgsqlDataSource db) { await using var cmd = db.CreateCommand("SELECT id,customer_id,status,total,created_at FROM ordering.orders ORDER BY created_at DESC"); await using var reader = await cmd.ExecuteReaderAsync(); var rows = new List<object>(); while (await reader.ReadAsync()) rows.Add(new { id = reader.GetGuid(0), customerId = reader.GetGuid(1), status = reader.GetString(2), total = reader.GetDecimal(3), createdAt = reader.GetFieldValue<DateTimeOffset>(4) }); return rows; }
    static async Task<CheckoutResult> ResultForOrder(NpgsqlDataSource db, Guid orderId, string? error = null) { await using var cmd = db.CreateCommand("SELECT status,subtotal,tax,delivery_fee,total FROM ordering.orders WHERE id=$1"); cmd.Parameters.AddWithValue(orderId); await using var reader = await cmd.ExecuteReaderAsync(); return await reader.ReadAsync() ? new CheckoutResult(orderId, reader.GetString(0), reader.GetDecimal(1), reader.GetDecimal(2), reader.GetDecimal(3), reader.GetDecimal(4), error) : new CheckoutResult(orderId, "PendingReservation", 0, 0, 0, 0, error); }
    public static async Task<List<Guid>> PendingOrders(NpgsqlDataSource db) { await using var cmd = db.CreateCommand("SELECT id FROM ordering.orders WHERE status='PendingReservation' AND created_at < now() - interval '30 seconds' ORDER BY created_at LIMIT 20"); await using var reader = await cmd.ExecuteReaderAsync(); var ids = new List<Guid>(); while (await reader.ReadAsync()) ids.Add(reader.GetGuid(0)); return ids; }
    public static async Task<SalesReport> Sales(NpgsqlDataSource db, DateTimeOffset? from, DateTimeOffset? to, string? status) { await using var cmd = db.CreateCommand("SELECT id,created_at,status,subtotal,tax,delivery_fee,total,currency FROM ordering.orders WHERE ($1 IS NULL OR created_at >= $1) AND ($2 IS NULL OR created_at < $2) AND ($3 IS NULL OR status=$3) ORDER BY created_at DESC"); cmd.Parameters.AddWithValue(NpgsqlTypes.NpgsqlDbType.TimestampTz, (object?)from ?? DBNull.Value); cmd.Parameters.AddWithValue(NpgsqlTypes.NpgsqlDbType.TimestampTz, (object?)to ?? DBNull.Value); cmd.Parameters.AddWithValue(NpgsqlTypes.NpgsqlDbType.Text, (object?)status?.Trim() ?? DBNull.Value); await using var reader = await cmd.ExecuteReaderAsync(); var rows = new List<SalesRow>(); while (await reader.ReadAsync()) rows.Add(new SalesRow(reader.GetGuid(0), reader.GetFieldValue<DateTimeOffset>(1), reader.GetString(2), reader.GetDecimal(3), reader.GetDecimal(4), reader.GetDecimal(5), reader.GetDecimal(6), reader.GetString(7))); var confirmed = rows.Where(x => x.Status == "Confirmed").ToList(); return new SalesReport(rows.Count, confirmed.Sum(x => x.Total), confirmed.Sum(x => x.Tax), confirmed.Sum(x => x.DeliveryFee), DateTimeOffset.UtcNow, rows); }
}
sealed class PendingOrderReconciler(IServiceProvider services, CatalogClient catalog, ILogger<PendingOrderReconciler> log) : BackgroundService { protected override async Task ExecuteAsync(CancellationToken stop) { while (!stop.IsCancellationRequested) { try { using var scope = services.CreateScope(); var db = scope.ServiceProvider.GetRequiredService<NpgsqlDataSource>(); foreach (var id in await OrderDb.PendingOrders(db)) { var reservation = await catalog.Reservation(id); if (reservation?.State == "Reserved") await OrderDb.Finish(db, id, "Confirmed", Guid.Empty, "Reservation reconciled", Guid.NewGuid(), true); else if (reservation?.State == "Failed") await OrderDb.Finish(db, id, "Rejected", Guid.Empty, "Reservation failed", Guid.NewGuid(), false); } } catch (Exception ex) { log.LogWarning(ex, "Pending-order reconciliation will retry"); } await Task.Delay(TimeSpan.FromSeconds(15), stop); } } }
sealed class OutboxPublisher(IServiceProvider services, IConfiguration config, ILogger<OutboxPublisher> log) : BackgroundService { protected override async Task ExecuteAsync(CancellationToken stop) { using var producer = new ProducerBuilder<string, string>(new ProducerConfig { BootstrapServers = config["Kafka:BootstrapServers"] ?? "localhost:9092", MessageTimeoutMs = 3000 }).Build(); while (!stop.IsCancellationRequested) { try { using var scope = services.CreateScope(); var db = scope.ServiceProvider.GetRequiredService<NpgsqlDataSource>(); await using var cmd = db.CreateCommand("SELECT event_id,payload::text FROM ordering.outbox WHERE published_at IS NULL ORDER BY occurred_at LIMIT 30"); await using var reader = await cmd.ExecuteReaderAsync(stop); var rows = new List<(Guid, string)>(); while (await reader.ReadAsync(stop)) rows.Add((reader.GetGuid(0), reader.GetString(1))); await reader.CloseAsync(); foreach (var row in rows) { await producer.ProduceAsync("order.events", new Message<string, string> { Key = row.Item1.ToString(), Value = row.Item2 }, stop); await using var done = db.CreateCommand("UPDATE ordering.outbox SET published_at=now() WHERE event_id=$1"); done.Parameters.AddWithValue(row.Item1); await done.ExecuteNonQueryAsync(stop); } } catch (Exception ex) { log.LogWarning(ex, "Order outbox publish will retry"); } await Task.Delay(TimeSpan.FromSeconds(3), stop); } } }
record OperationalMetrics(long OutboxPending, long PendingReservations);
static class MigrationSql { public static Task<string> BaselineAsync() => File.ReadAllTextAsync(Path.Combine(AppContext.BaseDirectory, "Migrations", "001_baseline.sql")); public static Task<string> CheckoutKeyAddressAsync() => File.ReadAllTextAsync(Path.Combine(AppContext.BaseDirectory, "Migrations", "002_checkout_key_address.sql")); }
static class DependencyHealth { public static async Task<IResult> Ready(NpgsqlDataSource db, IConfiguration cfg, string service) { try { await using var cmd = db.CreateCommand("SELECT 1"); await cmd.ExecuteScalarAsync(); using var kafka = new AdminClientBuilder(new AdminClientConfig { BootstrapServers = cfg["Kafka:BootstrapServers"] ?? "localhost:9092", SocketTimeoutMs = 2000 }).Build(); var metadata = kafka.GetMetadata(TimeSpan.FromSeconds(2)); if (metadata.Brokers.Count == 0) throw new InvalidOperationException("Kafka has no available broker."); return Results.Ok(new { status = "ready", service, dependencies = new { postgres = "ready", kafka = "ready" } }); } catch { return Results.Problem("A required dependency is unavailable.", statusCode: StatusCodes.Status503ServiceUnavailable); } } }
sealed class RequestMetrics { long _requests; long _errors; long _durationTicks; public void Record(int status, TimeSpan duration) { Interlocked.Increment(ref _requests); if (status >= 500) Interlocked.Increment(ref _errors); Interlocked.Add(ref _durationTicks, duration.Ticks); } public string AsPrometheus(string service, OperationalMetrics? operational = null) => $"# TYPE marketflow_http_requests_total counter\nmarketflow_http_requests_total{{service=\"{service}\"}} {_requests}\n# TYPE marketflow_http_errors_total counter\nmarketflow_http_errors_total{{service=\"{service}\"}} {_errors}\n# TYPE marketflow_http_request_duration_seconds summary\nmarketflow_http_request_duration_seconds_sum{{service=\"{service}\"}} {TimeSpan.FromTicks(_durationTicks).TotalSeconds.ToString(System.Globalization.CultureInfo.InvariantCulture)}\nmarketflow_http_request_duration_seconds_count{{service=\"{service}\"}} {_requests}\n# TYPE marketflow_outbox_pending gauge\nmarketflow_outbox_pending{{service=\"{service}\"}} {operational?.OutboxPending ?? 0}\n# TYPE marketflow_pending_reservations gauge\nmarketflow_pending_reservations{{service=\"{service}\"}} {operational?.PendingReservations ?? 0}\n"; }
static class OpenApi { public record Route(string Method, string Path, string Summary); public static string Document(string title, params Route[] routes) => JsonSerializer.Serialize(new { openapi = "3.0.3", info = new { title, version = "1.0.0" }, paths = routes.GroupBy(route => route.Path).ToDictionary(group => group.Key, group => group.ToDictionary(route => route.Method, route => new { summary = route.Summary, responses = new Dictionary<string, object> { ["200"] = new { description = "Successful response" } } })) }); public const string Ui = """<!doctype html><html><head><title>MarketFlow API</title><link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css"></head><body><div id="swagger-ui"></div><script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script><script>SwaggerUIBundle({url:'openapi/v1.json',dom_id:'#swagger-ui'});</script></body></html>"""; }
